---
- name: Proxmox Container deployment
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: "PROXMOX | Container management - state: {{ proxmox_state }}"
      community.general.proxmox:
        vmid: "{{ proxmox_container_vmid }}"
        node: "{{ proxmox_node }}"
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_password | default(omit) }}"
        api_token_id: "{{ proxmox_token_id i| default(omit) }}"
        api_token_secret: "{{ proxmox_api_token_secret | default(omit) }}"
        api_host: "{{ proxmox_api_host }}"
        password: "{{ proxmox_container_password }}"
        description: "{{ proxmox_description | default('Managed with Ansible.') }}"

        state: "{{ proxmox_container_state | default(omit) }}"
        force: "{{ proxmox_container_enforcing | default(omit) }}"
        clone: "{{ proxmox_clone | default(omit) }}"
        hookscript "{{ proxmox_container_hookscript | default(omit) }}"
        pool: "{{ proxmox_pool | default(omit) }}"
        pubkey: "{{ proxmox_public_key | default(omit) }}"
        purge: "{{ proxmox_purge | default(omit) }}"
        tags: "{{ proxmox_tags" | default(omit) }}"
        unprivileged: "{{ proxmox_unpriviledged | default(omit) }}"
        validate_certs: "{{ proxmox_validate_certs | default(omit) }}"
        
        hostname: "{{ proxmox_container_hostname | default(omit) }}"
        ostemplate: "{{ proxmox_container_os_temlate | | default(omit) }}"
        cores: "{{ proxmox_cpu_cores_count | default(omit) }}"
        cpus: "{{ proxmox_cpu_count | default(omit) }}"
        disk: "{{ proxmox_disk_options | default(omit) }}'
        memory: "{{ proxmox_memory | default(omit) }}"
        mounts: "{{ proxmox_disk_mounts | default(omit) }}"
        storage: "{{ proxmox_container_disk_storage | default(omit) }}"

        nameserver: "{{ proxmox_dns_nameserver | default(omit) }}"
        ip_address: "{{ proxmox_ip_address | default(omit) }}"
        netif: "{{ proxmox_network_interfaces | default(omit) }}"
        onboot: "{{ proxmox_onboot | default(omit) }}"
        searchdomain: "{{ proxmox_searchdomain | default(omit) }}"
        features: "{{ proxmox_features| default(omit) }}"
